services:
  postgres: #internal hostname within docker compose network
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"  #Host port:container port
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5431:80"
    depends_on:
      - postgres
  recipe-backend:
    image: recipe-service:latest
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
networks:
  app-network:
volumes: #to persist data
  postgres_data:
